### ISSUE TITLE
High severity network attack vector in multipart implementation

### ISSUE THREAD

**Issue by peterschutt** [abersheeran/baize#56]
Hi,

An embargo for a DoS vector affecting the werkzeug multipart implementation expired on the 14th of Feb. I recall from following along with [this Starlite issue](https://github.com/starlite-api/starlite/issues/466) that your implementation followed the werkzeug pattern, and so I believe your implementation may also be vulnerable.

You can read werkzeug's security advisory [here](https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323) and see their patch [here](https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1).

**Comment by abersheeran** [comment]
😯 Thanks!
