### ISSUE TITLE
Clarify copyright of the multipart parser

### ISSUE THREAD

**Issue by defnull** [abersheeran/baize#71]
Looks like the included multipart parser is based on werkzeug (BSD-3-Clause license) and should be credited accordingly. 

https://github.com/abersheeran/baize/blob/master/baize/multipart.py
https://github.com/pallets/werkzeug/blob/2.0.2/src/werkzeug/sansio/multipart.py

**Comment by abersheeran** [comment]
https://github.com/abersheeran/baize/commit/4df011a5db6677691d09364bca06d16f82ea759c
